server.port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: foo
        uri: http://example.com
        predicates:
        - CloudFoundryRouteService=
        filters:
        - RequestHeaderToRequestUri=X-CF-Forwarded-Url
        - SecureHeaders=
        - Logging=
management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#  level:
#    org.springframework.cloud.gateway: debug